### ISSUE TITLE
None of the callbacks are firing

### ISSUE THREAD

**Issue by lawrencetvo** [troybetz/react-youtube#101]
Hello all,

I'm not entirely sure I'm using the package correctly but doing 

`
      <Youtube
        videoId={ videoID }
        onPause={ () => console.log("FIRED") }
      />
`

doesn't produce a log in the console when I pause the video.

Repo can be found [here](https://github.com/lawrencetvo/watch-yt-together).

**Comment by tjallingt** [comment]
I'm sorry that it took me a while to reply, I opened the notification and then forgot about it 😕.
Since you closed the issue; did you manage to fix the problem?

**Comment by lawrencetvo** [comment]
@tjallingt Yeah, I figured it out, it was something with my bundle.js going to the wrong place.
