### ISSUE TITLE
Feature Request (if possible) - Track what % of the video was played.

### ISSUE THREAD

**Issue by texaspacm** [troybetz/react-youtube#104]
If there is a way to get the length of the video, and compare to what the user watched.  You have to figure how where they stopped playing.  There are different ways a video can stop.

1) Pause and not play again.
2) Navigate to another page.  
??

Great job.  If I end up using it, i'll let you know.

**Comment by lawrencetvo** [comment]
Can work on this functionality if mods approve.

**Comment by tjallingt** [comment]
https://github.com/tjallingt/react-tjube/blob/master/src/components/ProgressBar/ProgressBar.jsx#L27-L36

Here is an example of how I calculate the progress on a video.
I'm not sure whether we should implement specific functionality within `react-youtube` for this as the YouTube IFrame API already allows you to calculate this yourself.

However I'm open to suggestions and if this is something people want we can implement it.

**Comment by anjitpariyar** [comment]
@tjallingt Current Approach Fails to Track Total Watched Duration
When a user uses seekTo() or clicks on the progress bar, currentTime instantly updates to the new position. This means your current method only reflects the latest point the user is at, not the sum of all the time they've watched across different segments.
Example:

    User watches from 0:00 to 1:00 (60 seconds watched).

    User seeks to 5:00.

    User watches from 5:00 to 6:00 (another 60 seconds watched).

Your current code would report the progress based on the last segment (e.g., 5:00 to 6:00), but it wouldn't inherently know that the user also watched from 0:00 to 1:00.

so is there a way to track the total watched time by user  ??
