### ISSUE TITLE
All videos breaking with create-react-app

### ISSUE THREAD

**Issue by mmmaaatttttt** [troybetz/react-youtube#105]
Hi there!

I've got some colleagues using `react-youtube` along with `create-react-app`, and until this week everything was working great. This week, however, everything seems to have broken. No videos will load, and the player screen looks like this:

<img width="1141" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3916770/24566999/a44a3d10-1610-11e7-8322-15e77ae4c8f0.png">

At first I thought something might be wrong with the project, but I also created a minimal working example just using `create-react-app` and `react-youtube`. Here's the repo for it: https://github.com/mmmaaatttttt/react-youtube-demo; all I did was add `react-youtube` to the project and try to add a video to the `App` component.

I noticed a dependency on `youtube-player`, but this appears to be working fine. The example has two videos side-by-side, one using `react-youtube` and one just using `youtube-player`; the latter video loads but the former doesn't.

Any idea what might be going on? Thanks.

**Comment by tjallingt** [comment]
I somehow did not receive a notification for this issue... I'm sorry for not responding in time.
Since you closed the issue I assume you managed to fix the problem?
