### ISSUE TITLE
video pauses when changing tab

### ISSUE THREAD

**Issue by ceres629** [troybetz/react-youtube#110]
If I start playing a video and change tab (in chrome) it pauses the video.

**Comment by ceres629** [comment]
is this meant to be a feature or is it indeed a bug?

**Comment by goto-bus-stop** [comment]
It's definitely not an intended feature! However I also can't reproduce it in any of the projects I've used react-youtube in.

Which Chrome version are you using?
Does it also happen with the example at http://troybetz.github.io/react-youtube/ for you? If not, could you share a small example project where this does occur?

**Comment by ceres629** [comment]
I'll give it another shot and see if i can get it working as I decided againts using react-youtube because i couldn't solve the issue initially. It doesn't seem to happen on the demo, so that suggests the problem was on my end. 

I was using it in rails however using the react-on-rails gem which may have something to do with it. . I will give it another try and see what I can uncover.

**Comment by ceres629** [comment]
It doesn't seem to be doing this anymore, not what the issue was before or what solved it but I guess I'll close this.

**Comment by goto-bus-stop** [comment]
OK, np! Thanks for getting back to us. Glad it works now :)
