### ISSUE TITLE
Error: Element type is invalid when attempting to use YouTube component

### ISSUE THREAD

**Issue by Kamil1** [troybetz/react-youtube#111]
I'm relatively new to React, so this might be an error on my behalf, but I'm at my wits end trying to figure out what is wrong here.

I installed using `npm install --save react-youtube`

My super super simple file is below:

```
import React from 'react';
import YouTube from 'react-youtube';

class YouTubeVideo extends React.Component {

    constructor(props) {
        super(props);
        this._onReady = this._onReady.bind(this)
    }

    render() {
        const opts = {
            height: '390',
            width: '640'
        }
        return(
            <YouTube videoId={this.props.youtube_video_id} opts={opts} onReady={this._onReady}/>
        )
    }

    _onReady(event) {
        if (this.props.startAt) event.target.seekTo(this.props.startAt, true)
        if (this.props.mute) event.target.mute()
        event.target.playVideo()
    }
}

export default YouTubeVideo;
```

Alas -- I receive this error:

`bundle.js:66730 Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of 'YouTubeVideo'.`

Any idea what gives?

The only thing I can think of causing this issue is the imports, but everything looks like it is being imported correctly! I've been staring at this for hours and I have no idea what could be happening.

**Comment by tjallingt** [comment]
Try logging `YouTube` to the console to see what this object is...
(in the constructor add `console.log(YouTube)`)

**Comment by Kamil1** [comment]
Hi @tjallingt -- thanks for the response.

I *am* able to log the object, which prints off the following in Chrome's console:

```const path = require('path')
const webpack = require('webpack')

module.exports = {
	devtools: 'eval-source-map',
	entry: [
		// For hot style updates
		'webpack/hot/dev-server',
		'webpack-hot-middleware/client',
		 './src/index'
	],
	output: {
		path: path.join(__dirname, 'public'),
		filename: 'bundle.js',
		publicPath: '/public/',
		historyApiFallback: {
			index: '/public/'
		}
	},
	devServer: {
		historyApiFallback: true
	},
	plugins:[
		new webpack.NoErrorsPlugin(),
		new webpack.optimize.OccurrenceOrderPlugin(),
		new webpack.HotModuleReplacementPlugin()
	],
	module: {
		loaders: [
			{
				test:/\.js$/, 
				include: [
					path.join(__dirname, 'src')
				], 	
				loaders: ['react-hot', 'babel']
			},
			{
			  test: /\.css$/,
			  loader: 'style-loader'
			}, {
			  test: /\.css$/,
			  loader: 'css-loader',
			  query: {
			    modules: true,
			    localIdentName: '[name]__[local]___[hash:base64:5]'
			  }
			}
		]
	},
	resolve: {
		extensions: ['.js']
	}
}
```

Furthermore, in VS Code, my text editor/IDE, I am able to see that the component is being properly linked, as I can "jump" into it. The typically "check" of removing the `import` statement causes the component to be "undeclared", and changing the import syntax to use `{}` also yields no improvements. I can see that `YouTube` is exported as a default class, so the curly brace import syntax shouldn't be required.

The app is build with webpack, and it uses babel. For completeness I've added my webpack config file below.

```
const path = require('path')
const webpack = require('webpack')

module.exports = {
	devtools: 'eval-source-map',
	entry: [
		// For hot style updates
		'webpack/hot/dev-server',
		'webpack-hot-middleware/client',
		 './src/index'
	],
	output: {
		path: path.join(__dirname, 'public'),
		filename: 'bundle.js',
		publicPath: '/public/',
		historyApiFallback: {
			index: '/public/'
		}
	},
	devServer: {
		historyApiFallback: true
	},
	plugins:[
		new webpack.NoErrorsPlugin(),
		new webpack.optimize.OccurrenceOrderPlugin(),
		new webpack.HotModuleReplacementPlugin()
	],
	module: {
		loaders: [
			{
				test:/\.js$/, 
				include: [
					path.join(__dirname, 'src')
				], 	
				loaders: ['react-hot', 'babel']
			},
			{
			  test: /\.css$/,
			  loader: 'style-loader'
			}, {
			  test: /\.css$/,
			  loader: 'css-loader',
			  query: {
			    modules: true,
			    localIdentName: '[name]__[local]___[hash:base64:5]'
			  }
			}
		]
	},
	resolve: {
		extensions: ['.js']
	}
}
```

**Comment by goto-bus-stop** [comment]
@Kamil1 It looks like you've accidentally pasted your webpack config twice instead of the result of `console.log(YouTube)`.

Your webpack config looks good, I don't think it's causing the problem. Can you share your babel config as well?

**Comment by Kamil1** [comment]
@goto-bus-stop Whoops, yes you are correct. Let me try logging the object again and update my original post. Regardless, I do believe I'm importing the code correctly as well.

My `.babelrc` file is below:
```
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "env": {
    "development": {
      "plugins": [["react-transform", {
        "transforms": [{
          "transform": "react-transform-hmr",
          "imports": ["react"],
          "locals": ["module"]
        }]
      }]],
	  "presets": [
        "react-hmre"
      ]
    }
  }
}
```

**Comment by goto-bus-stop** [comment]
Thanks! I'm not familiar with react-transform myself, but it looks like the `react-hmre` preset already configures that plugin here: https://github.com/danmartinez101/babel-preset-react-hmre/blob/master/index.js So it's added twice. I don't know if that could be related but it might be worth a shot to remove the `react-transform` part:

```json
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "env": {
    "development": {
      "presets": [
        "react-hmre"
      ]
    }
  }
}
```

**Comment by Kamil1** [comment]
@goto-bus-stop Thanks for the suggestion!

I replaced my `.babelrc` file the one you've attached above, and unfortunately I'm encountering the same error 😞 

A screenshot of the logging + error message is below.

<img width="1631" alt="screen shot 2017-04-26 at 9 43 09 am" src="https://cloud.githubusercontent.com/assets/7742640/25446033/fd0dabc2-2a64-11e7-913e-1b3985505d27.png">

I am able to successfully import and use dependencies from places (such as `axios` for requests), which makes this issue even more difficult for me to figure out.

Could it be that my `npm run build` script is wrong?

`"build": "cross-env NODE_ENV=development webpack --config ./webpack.dev.config.js --progress --colors"`

**Comment by tjallingt** [comment]
Hello @Kamil1 I'm sorry for the delay in getting back to you.
Are you still experiencing this issue?
If so could you share the code that is generating the error? so I'd like to see the code in bundle.js where the error is triggered (which should be the render method of your YouTubeVideo class).
