### ISSUE TITLE
Change the current time 

### ISSUE THREAD

**Issue by adrian410** [troybetz/react-youtube#112]
Hello,

Do you know if there is a way to SET/CHANGE the current time of the video ?
How do you get the youtube player variable ?

I'm new to react and i'm not sure, i didn't find anything about it in your doc.

Thanks for your help !

**Comment by tjallingt** [comment]
Hello,

You need to obtain a reference to the YouTube Iframe API like shown here: https://github.com/troybetz/react-youtube/blob/master/example/example.js#L23-L28

Then you can use `player.seekTo(seconds:Number, allowSeekAhead:Boolean):Void` method of the YouTube IFrame API to set the current time of the video: https://developers.google.com/youtube/iframe_api_reference#Playback_controls

**Comment by adrian410** [comment]
Thanks a lot ! That was very helpfull and well explained !
