### ISSUE TITLE
an example to access event.data?

### ISSUE THREAD

**Issue by artndes9** [troybetz/react-youtube#116]
sorry for newbie question and i am new to React, just point me to right direction...

how do i access player States like 
YT.PlayerState.ENDED,
YT.PlayerState.PLAYING,
and get player.getCurrentTime()?

**Comment by tjallingt** [comment]
our example application shows you how to get a simple application up and running:
https://github.com/troybetz/react-youtube/blob/master/example/

Here is an implementation of a custom progressbar for react-youtube that you could look at (for `player.getCurrentTime()` specifically): https://github.com/tjallingt/react-tjube/blob/master/src/components/ProgressBar/ProgressBar.jsx#L27-L36

The `YT` object is accessable globally but we include them in the import as well so you can write:
```js
import YouTube from 'react-youtube';
console.log(YouTube.PlayerState.PLAYING == YT.PlayerState.PLAYING); // true
```
