### ISSUE TITLE
Full width

### ISSUE THREAD

**Issue by LeBovin** [troybetz/react-youtube#122]
Hey,
How could the player use all avaible space ?
Using:
```
{
  width: '100%',
  height: '100%'
}
```

doesn't force the player use all the container's space. (it is even smaller)
Thanks for any answer

**Comment by tjallingt** [comment]
https://github.com/tjallingt/react-tjube/blob/master/src/components/Player/Player.jsx/

https://github.com/tjallingt/react-tjube/blob/master/src/components/VideoAppPlayer.css#L1-L8

In combination with the highlighted CSS applied to your YouTube component you should be able to get it full screen.

**Comment by SEAjamieD** [comment]
Thank you for this!  Just used and worked like a charm.  And also thanks for maintaining this, it's really great!
