### ISSUE TITLE
Intermittent flickering

### ISSUE THREAD

**Issue by troycroz** [troybetz/react-youtube#125]
Have there been any reports of the video flickering?

I've observed this a couple times, but have been unable to reproduce it. Was wondering if this has been observed by others.

**Comment by tjallingt** [comment]
I have not heard of or seen anything like you describe.
If you find out more please let us know.

**Comment by Sburke0708** [comment]
@troycroz I've seen this in facebook videos too. i'm on a mac and using chrome. Can't seem to get to the bottom of this, but I don't think it's related to this component.
