### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by mikelambert** [troybetz/react-youtube#130]
Hey there, sorry to bug, but is it possible to get an npm release of this?

Unfortunately the way the package is set up, I cannot depend on the github version from my `package.json`. (Namely, your `package.json` points at `dist/YouTube.js`, which is not available on a github checkout, and so the package fails to load.)

(I'm mainly interested in the lodash cleanup, and depending on a version which will pull that in properly into my web build.)

**Comment by tjallingt** [comment]
http://lmgtfy.com/?q=npm+react-youtube

**Comment by mikelambert** [comment]
Sorry, I should have requested an _updated_ npm release of this. The published version does not have my recent commit to this repo.

**Comment by tjallingt** [comment]
My bad, totally forgot about it.
Should be up now as 7.5.0 (accidentally also made a 7.4.1 but whatever)
