### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by panppp119** [troybetz/react-youtube#132]
I've got an error "Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('website_url)."

How can I fix it? Please help.

**Comment by tjallingt** [comment]
see: https://github.com/troybetz/react-youtube/issues/128

This error is generated inside youtubes embed javascript meaning we cannot fix it and it does not affect the functionality of the youtube iframe api.
