### ISSUE TITLE
Android: play can only be initiated by a user gesture

### ISSUE THREAD

**Issue by leogout** [troybetz/react-youtube#135]
Hello,

The youtube player on mobile isn't recognizing the `playVideo()` method as an user input and It is blocked with the following warning:
"Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture."
I've also tried `{ autoplay:` ~~true~~ `1 }` in the opts without success.
In my app, it is initialized by a "user gesture" but the player can't know that. Do you know any workarounds ?

By the way, thank you for this amazing project !

**Comment by tjallingt** [comment]
Seeing as you wrote `{autoplay: true}` can you confirm that your opts object is what the Youtube IFrame API expects?

More information about the opts object can be found here:
https://developers.google.com/youtube/player_parameters?playerVersion=HTML5

and a working example of the autoplay option can be found in the readme of this project:
https://github.com/troybetz/react-youtube#example

**Comment by leogout** [comment]
Oh sorry, that's a typo in my post, i've fixed it. I've tried, every combinaisons of "autoplay" option and "playerReady" method. This is a sample of the code I used:
```js
 <YouTube videoId={video.id}
          onReady={this.onPlayerReady}
          opts={{
            height: '200',
            width: '200',
            playerVars: {
              autoplay: 1
            }
          }}
/>
```

The `playerReady` method: 
```js
onPlayerReady(event) {
  this.setState({
    isFetching: false,
    player: event.target,
  })
  event.target.playVideo()
}
```

This issue seems related [to this](https://stackoverflow.com/questions/38791760/domexception-play-can-only-be-initiated-by-a-user-gesture).

**Comment by leogout** [comment]
Hello, any inputs about this ?

**Comment by tjallingt** [comment]
Hey since there was a long period of inactivity on this issue (and no response since my last suggestion) i figured it would be okay to close it... The documentation of the youtube iframe api now contains a note regarding this issue: https://developers.google.com/youtube/iframe_api_reference#Mobile_considerations

**Comment by leogout** [comment]
Okay no problem! Thanks for this, I'll have a look.

Cheers!
