### ISSUE TITLE
Is there a way to start the video in the middle?

### ISSUE THREAD

**Issue by pkellner** [troybetz/react-youtube#137]
That is, I'd like to be able to update a prop and have the video start playing in the middle.

Something like:

<YouTube
       videoId="XyG6wo_iV-Y?t={this.state.currentTime}"
       ...

**Comment by tjallingt** [comment]
Yes there is, check the official youtube iframe api documentation for more information about the options it offers as this component is just a simple wrapper ontop of that. 
see: https://developers.google.com/youtube/player_parameters?playerVersion=HTML5#start
