### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow' when logged in to Google

### ISSUE THREAD

**Issue by umutozdemir97** [troybetz/react-youtube#140]
When I log in to my google account and visit the page (http://localhost:3000) where react-youtube component is there, I get an error: 

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://localhost:3000').`

In incognito mode, there is no such error. Options are: 

```
    const opts = {
      playerVars: {
        autoplay: 0,
        controls: 2
      }
    };
```

And in some situations where I can't determine, there is no error. For example, after a few reload button clickings, I differently clicked the url bar and pressed enter, then the error appeared in console again. 

Video is working and I have tested events for video start, end and all others. They are working quite well. I don't know the result of this error in my page.

**Comment by tjallingt** [comment]
It is harmless and we can't fix it, see other issues:
https://github.com/troybetz/react-youtube/issues?q=is%3Aissue+postmessage

Note: maybe we should add a section to the readme for this
