### ISSUE TITLE
Unrecognized feature: 'autoplay'.

### ISSUE THREAD

**Issue by rockmandash** [troybetz/react-youtube#144]
![image](https://user-images.githubusercontent.com/7580792/35716277-db6396d0-0812-11e8-91ee-41e8781d21f1.png)
I don't know what is going on, seem like youtube has chage a little bit of their api.

**Comment by JonathanWbn** [comment]
It might be related to Googles [autoplay policy changes](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) that came into effect January 2018.

A workaround, for now, is this: `onReady={event => event.target.playVideo()}`

**Comment by rockmandash** [comment]
@JonathanWbn 
Thanks for your reply.
Sadly, after adding event.target.playVideo(), the warning still exist.

**Comment by JonathanWbn** [comment]
Event when you turn `autoplay` to `0`?

Either way, as discussed [here](https://stackoverflow.com/questions/48247002/unrecognized-feature-autoplay-error-with-youtube-embedded-player), this warning seems to be a bug on Googles side.

**Comment by rockmandash** [comment]
Yes, "autoplay 0" is not fixing the waring

**Comment by dbrkani** [comment]
any update on this?

**Comment by AtnesNess** [comment]
any update on this?

**Comment by tjallingt** [comment]
No, I'm not sure why/how this is happening. I'm sorry but this is on Google/Youtube's end, nothing i can do 😞
