### ISSUE TITLE
Add widget_referrer to the props

### ISSUE THREAD

**Issue by marhalpert** [troybetz/react-youtube#147]
https://developers.google.com/youtube/player_parameters#widget_referrer

**Comment by tjallingt** [comment]
You can already pass this using the opts prop:

```jsx
<YouTube
  videoId="2g811Eo7K8U"
  opts={{
    playerVars: {
      widget_referrer: 'example.com'
    }  
  }}
  onReady={this._onReady}
/>
```

If you can make a compelling argument for why this should be a direct prop instead of allowing users to pass through options exactly like the youtube iframe api we can think about defining props for this and other playerVars.
