### ISSUE TITLE
`containerClassName` prop does not exist

### ISSUE THREAD

**Issue by sarneeh** [troybetz/react-youtube#148]
Just like in the title. I don't have any control on the container in this situation.

EDIT:
I've just noticed that this package has not released any new version for 6 months. The code and docs changed a little bit so it's really confusing using this library as many things described in the documentation do not exist in the newest version of `react-youtube`

**Comment by tjallingt** [comment]
Ah, excuse me i'll update it on NPM in a few hours!
I just plain forgot 😞 after merging the latest pull request...

**Comment by sarneeh** [comment]
Awesome news! :)

**Comment by tjallingt** [comment]
@sarneeh Gotcha!
