### ISSUE TITLE
How to control the video player via this package

### ISSUE THREAD

**Issue by phakphumi** [troybetz/react-youtube#150]
I would like to know how to play, pause, stop, increase video speed, play next video in this package.
Anyone has an example

**Comment by tjallingt** [comment]
check out the example folder for a more complete example but the onready event gives you access to the youtube object:

**Comment by tjallingt** [comment]
check out the example folder for a more complete example but the onready event gives you access to the youtube object:

https://github.com/troybetz/react-youtube/blob/master/example/example.js#L23-L28

you can then use any of the youtube player api methods on that to control the youtube player https://developers.google.com/youtube/iframe_api_reference#Functions

Hope this helps
