### ISSUE TITLE
Set the url value manually

### ISSUE THREAD

**Issue by edwinharly** [troybetz/react-youtube#156]
I read that the url props was replaced by videoId, but is there still some way to set the url manually ? The reason is that I want to use the search query (`https://www.youtube.com/embed?listType=search&list=QUERY`)

**Comment by tjallingt** [comment]
You can set the list and listType through the `playerVars` option of the youtube iframe api: https://developers.google.com/youtube/player_parameters?playerVersion=HTML5#list

```jsx
<YouTube
  videoId="2g811Eo7K8U"
  opts={{
    list: 'QUERY',
    listType: 'search',
  }}
  onReady={this._onReady}
/>
```

**Comment by edwinharly** [comment]
@tjallingt is that `videoId` necessary ? It doesn't work when I delete the `videoId`, from the [documentation](https://developers.google.com/youtube/player_parameters?playerVersion=HTML5#Selecting_Content_to_Play), I think that the `videoId` won't be necessary if using search

**Comment by tjallingt** [comment]
Great to hear that!
