### ISSUE TITLE
Video Unavailable, where trying to play

### ISSUE THREAD

**Issue by acmoune** [troybetz/react-youtube#158]
The Video thumbnail loads well, then when I try to play, it does like it is about to launch the video, then I get this screenshot. But of course, the video plays well on youtube.

any idea on what is going wrong ? It works well on my local dev machine. this is a screenshot from prod environment.
 
![yt-err](https://user-images.githubusercontent.com/8550711/44467729-8164e100-a61b-11e8-9d3c-8bc46fc952fd.png)

**Comment by tjallingt** [comment]
Hmm thats strange, can you check out if there are any warnings in your javascript console?

**Comment by acmoune** [comment]
Noting except this

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('http://server:8080').
```

But I think I use to have it even with `localhost`

**Comment by tjallingt** [comment]
yea that message isn't unusual and doesnt seem to affect functionality of react-youtube...

is it only for that video? maybe embedding is disabled for that video (which should give a different error but maybe they changed something).

**Comment by acmoune** [comment]
.I tried 2 videos that use to work on localhost, I got the same thing.

**Comment by acmoune** [comment]
I close this, since the issue is not from the module. But if you have any suggestion, please do not hesitate to post.

**Comment by Rickmey** [comment]
@acmoune

I have the same issue. After some investigation I found it's more or less random if you get the video. Refresh the site and sometimes the video will be availabel.

I assume it's an issue with the YouTube data servers. Genereally the video exists but not on the server you're routed to. I encountered four different displays of "video unavailbale".
I'm currently trying to implement a workaround by requesting multiple times until the video is available. I will let you know if I had any luck.

**Comment by acmoune** [comment]
@Rickmey  Thank you. What I observed is that some videos always run well, and others others show that error. I tried to refresh many times.

But I am wondering why all those videos run well from localhost. 

Maybe youtube allows to disable broadcasting from others servers on internet, but as long as you run on localhost it works. But if refreshing many many times can make it run as you say, then I am wrong and it might possibly be an issue with youtube servers, but that would be very strange from Google...

Anyway my actual workaround is to load only the working videos.
If you successfully implement you work around, I will be the first to try it !
Thanks.

**Comment by staticGuru** [comment]
YouTube's default UI elements can be hidden, related videos can be hidden, and ads can be removed from YouTube videos in react native.

It may help you to meet your requirements if you use the below-mentioned package:
https://www.npmjs.com/package/react_native_youtube_streamer

Besides being open source, the package is scalable as well. It is also possible for you to contribute to that project.
