### ISSUE TITLE
Player not working in the production build

### ISSUE THREAD

**Issue by gaveen5555** [troybetz/react-youtube#165]
I got this library to work on my localhost but it is not working in the production build. What can be the reason for this?

The error i'm getting is

main.0ebe5793.js:sourcemap:1 Refused to load the script 'https://www.youtube.com/iframe_api' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by tjallingt** [comment]
Whatever you are using to host your production build is setting the CSP header and blocking any external scripts from being loaded. react-youtube loads the youtube iframe api when it is mounted from youtube.com so you need to whitelist scripts from youtube...

**Comment by gaveen5555** [comment]
headers {
    contentSecurityPolicy = "img-src 'self' data:; default-src 'self'"
  }

This is how i've set my CSP

**Comment by tjallingt** [comment]
you might want to add `script-src youtube.com;`
