### ISSUE TITLE
Prop error when using playlist

### ISSUE THREAD

**Issue by NoxHarmonium** [troybetz/react-youtube#170]
We are using the component to play a playlist like so:

       <YouTube
          opts={{
            playerVars: {
              autoplay: 1,
              listType: 'playlist',
              list: 'xxxxxxxxxxxxxxx'
            }
          }}
        />

It works fine, but we get a prop warning from React in the console:

    Warning: Failed prop type: The prop `videoId` is marked as required in `YouTube`, but its value is `undefined`.

Our workaround was to just set "videoId" to an empty string which suppresses the error.

I can think of two solutions off the top of my head:

- Make "videoId" optional 
- Add a dedicated playlist property to the component

If you like either of those solutions I'll be happy to help make the change and raise a PR.

Thanks

**Comment by lilybarrett** [comment]
Agreed. I'm using a randomizer function to render a random video on each page render, and currently, while everything works well/otherwise looks good, I'm seeing this error pop up before the player's initial render. I'm not sure if it would make total sense to make `videoId` an optional parameter, since we do need it to display a video, but could we somehow account for this initial render issue?

**Comment by tjallingt** [comment]
Oh sorry didn't catch this until now.

Making videoId optional seems better to me than exposing a new prop/api for playlists. Although we do nees to make sure the player is not loaded into an unexpected state (for example just not showing anything).

If either of you would submit a pull request for that i'd be happy to merge it :)

**Comment by lilybarrett** [comment]
On it.

**Comment by lilybarrett** [comment]
Made the change. Ran the tests and the example, and all seemed good. Would you be willing to test it out, as well, to make sure I haven't missed anything? Here's the PR: https://github.com/troybetz/react-youtube/pull/182

**Comment by lilybarrett** [comment]
@tjallingt What's the status of this change?

**Comment by tjallingt** [comment]
excuse me for the inactivity...
everything looks fine to me so I just published it on NPM 🚢 

gonna close this issue now :)
