### ISSUE TITLE
Changing player volume

### ISSUE THREAD

**Issue by walkerreynolds16** [troybetz/react-youtube#172]
Is there a way to change the volume of the embedded player?

**Comment by tjallingt** [comment]
You can find instructions in the official youtube iframe api documentation here: https://developers.google.com/youtube/iframe_api_reference#Playback_controls

> ### Changing the player volume
> `player.mute():Void`
> Mutes the player.
>
> `player.unMute():Void`
> Unmutes the player.
>
> `player.isMuted():Boolean`
> Returns true if the player is muted, false if not.
>
> `player.setVolume(volume:Number):Void`
> Sets the volume. Accepts an integer between 0 and 100.
>
> `player.getVolume():Number`
> Returns the player's current volume, an integer between 0 and 100. Note that getVolume() will return the volume even if the player is muted.

You can check the example for more details on how to get access to the player object: https://github.com/troybetz/react-youtube/blob/master/example/example.js#L23-L28
