### ISSUE TITLE
error installing u-wave-cli

### ISSUE THREAD

**Issue by StepIg** [troybetz/react-youtube#174]
i got this error on installing:
npm ERR! code E404
npm ERR! 404 Not Found: u-wave-cli@latest

**Comment by tjallingt** [comment]
> Closed? What a support! :-D

Since you opened two issues at the same time i felt i could help you better in the other one since the amount of information provided here is quite limited...

Also u-wave is/was a depend_end_ of react-youtube so it is unlikely that the issue is related to react-youtube.
