### ISSUE TITLE
Restricted Videos

### ISSUE THREAD

**Issue by walkerreynolds16** [troybetz/react-youtube#177]
This is more of a question rather than a problem. I got my site, which contains this youtube player, into a production server. When i try to load certain videos such as many music videos, the player shows "video unavailable - This video contains content from $$$, who has blocked it from display on this website or application". This makes since why companies wouldn't want their videos being displayed on random sites but it there a way to bypass this? I've seen sites like PlugDJ who have the ability to play almost any videos they want, including videos that are blocked on my site. Any input would be great.

**Comment by panchicore** [comment]
how did you do @walkerreynolds16 ?
