### ISSUE TITLE
IE 10 & 11 issue - Promise is undefined

### ISSUE THREAD

**Issue by Vuice** [troybetz/react-youtube#179]
I am running the example (npm run example) locally and getting the following error in the console in IE 10:

SCRIPT5009: 'Promise' is undefined

I was reading an issue with another player (react-player) that required a polyfill (https://github.com/CookPete/react-player/issues/39).  Is it possible to apply to this player as well?

**Comment by tjallingt** [comment]
yea you probably need a polyfill (or [ponyfill](https://github.com/sindresorhus/ponyfill)) such as: https://www.npmjs.com/package/es6-promise or https://www.npmjs.com/package/pinkie-promise
