### ISSUE TITLE
Is it possible to remove the "More videos" tab?

### ISSUE THREAD

**Issue by guerrap** [troybetz/react-youtube#184]
Is it possible to hide or change the behavior on the click event of the "More videos" tab that opens up when the video is paused? I ask this because if you want to build your YouTube like app and click on one of the videos in the "More videos" tab you get redirected to YouTube itself, outside of your app. Maybe I misunderstood this component, that should be used just as a widget for a single video.

**Comment by Komsomol** [comment]
It doesn't look like it is possible anymore after Youtube [deprecated the rel=0 parameter in playerVars object](https://developers.google.com/youtube/player_parameters#release_notes_08_23_2018). This change is not something this react component controls.

**Comment by jDeppen** [comment]
This won't remove "More videos" but it will only show videos from the same channel
```
const opts = { playerVars: { rel: 0 } }
```
