### ISSUE TITLE
no-cookie option

### ISSUE THREAD

**Issue by vedran-brnjetic** [troybetz/react-youtube#185]
I ended up here from juliussohn/react-youtube-background which uses your component as the basis for their component. 

Can you add a possibility to use **www.youtube-nocookie.com** as the source of the video, just without cookies, to [make use of YouTube's enhanced privacy](https://www.ghacks.net/2018/05/23/why-you-should-always-use-youtubes-privacy-enhanced-mode/)? Either by default or through an optional parameter.

(I also opened an issue about that in the [basis of your component](https://github.com/gajus/youtube-player/issues/79) , just hoping that you will find a way to accept a no-cookie parameter from 
the [component which extends yours](https://github.com/juliussohn/react-youtube-background/issues/5) and pass it on to the youtube-player component.

Thank you.

**Comment by vedran-brnjetic** [comment]
I finally found time to dig through this myself and discovered that by passing `{host: "https://www.youtube-nocookie.com"}` in opts object makes this happen.

I'm closing this issue and hope it helps someone else.

**Comment by borisrorsvort** [comment]
As mentioned in https://axbom.com/embed-youtube-videos-without-cookies/, the no-cookie mode still stores a local storage device id that is, without consent, non gdpr compliant.

**Comment by bdefore** [comment]
If the `https` schema is not provided (i.e. providing a `host` of `//www.youtube-nocookie.com`), `onEnd` and potentially other handlers do not fire.

**Comment by borisrorsvort** [comment]
What would be nice is to implement something like that: 

![](https://axbom.com/content/images/2021/03/youtube-consent-cookies-tracking-video-2.png)
