### ISSUE TITLE
How can I get the current time of the video?

### ISSUE THREAD

**Issue by utkarshdubey** [troybetz/react-youtube#191]
How can I get the current time or duration of the video iframed? Is there any method? If yes, then please tell the code for it too.

**Comment by 42x42x42** [comment]
you could set your own time counter on function onStateChange which is provided(dont forget to pause your counter when video is paused or buffering)

**Comment by utkarshdubey** [comment]
@42x42x42 There are the native Youtube API calls such as player.getCurrentTime(). can't I access using them?

**Comment by 42x42x42** [comment]
@utkarshdubey, I didn't knew about that call . Have checked it and it works too

**Comment by tjallingt** [comment]
You can find instructions in the official youtube iframe api documentation here: https://developers.google.com/youtube/iframe_api_reference#Playback_status

> ### Playback status
> `player.getCurrentTime(): Number`
> Returns the elapsed time in seconds since the video started playing.
>
> ### Retrieving video information
> `player.getDuration(): Number`
> Returns the duration in seconds of the currently playing video. Note that getDuration() will return 0 until the video's metadata is loaded, which normally happens just after the video starts playing.
>
> If the currently playing video is a live event, the getDuration() function will return the elapsed time since the live video stream began. Specifically, this is the amount of time that the video has streamed without being reset or interrupted. In addition, this duration is commonly longer than the actual event time since streaming may begin before the event's start time.

You can check the example for more details on how to get access to the player object: https://github.com/troybetz/react-youtube/blob/master/example/example.js#L23-L28

**Comment by utkarshdubey** [comment]
No there aren't. The thing is player is not defined and this is the main problem.

**Comment by tjallingt** [comment]
please check out this example that shows how to get access to the `player`: https://github.com/troybetz/react-youtube/blob/master/example/example.js#L23-L28

**Comment by liuweiming1997** [comment]
HI bro, does anyone knows how to `getCurrentTime` at each frame? just like the HTML5  `<Video />` method: `ontimeupdate`. Thanks all. I don`t see any method to achieve it.

**Comment by 42x42x42** [comment]
> HI bro, does anyone knows how to `getCurrentTime` at each frame? just like the HTML5 `<Video />` method: `ontimeupdate`. Thanks all. I don`t see any method to achieve it.

https://developers.google.com/youtube/iframe_api_reference#Playback_status check this,a lot of time has passed since I worked with it and don't remember details

**Comment by liuweiming1997** [comment]
> > HI bro, does anyone knows how to `getCurrentTime` at each frame? just like the HTML5 `<Video />` method: `ontimeupdate`. Thanks all. I don`t see any method to achieve it.
> 
> https://developers.google.com/youtube/iframe_api_reference#Playback_status check this,a lot of time has passed since I worked with it and don't remember details

[correct me if I am wrong] I think this is not a callback method, so it can`t feedback the current_time to our page correctly.
