### ISSUE TITLE
Component stops updating when you change the url before onReady

### ISSUE THREAD

**Issue by tjallingt** [troybetz/react-youtube#36]
It seems that the component stops updating when you change the url before the onReady event of the player.
I'm building something where you can press a "next video" button, when used normally there is no problem however when you spam the button the component stops changing videos.
It also happens when I update the video in "componentDidMount"; I load the player with the url '' (empty string) and then load the actual url from sessionStorage in componentDidMount because componentDidMount happens very rapidly after the initialization of the component it changes the video url before the onReady and stops the component from updating.

**Comment by tjallingt** [comment]
I can consistently reproduce this error using this code. I expect this to load the video `Rick Astley - Never Gonna Give You Up` but instead it loads the first video `Trolling Saruman`.
```
import React from 'react';
import ReactDOM from 'react-dom';
import YouTube from './react-youtube/src/YouTube.js';

export default class Test extends React.Component {
	state = { 
		video: 'http://youtu.be/KaqC5FnvAEc'
	};

	constructor( props ) {
		super( props );
	}

	componentDidMount() {
		this.setState({video: 'http://youtu.be/dQw4w9WgXcQ'});
	}

	onReady( event ) {
		console.log( "onReady", event, this.state );
	}

	onPlay( event ) {
		console.log( "onPlay", event, this.state );
	}

	onPause( event ) {
		console.log( "onPause", event, this.state );
	}

	onEnd( event ) {
		console.log( "onEnd", event, this.state );
	}

	onError( event ) {
		console.log( "onError", event, this.state );
	}

	render() {
		const opts = {};

		return(
			<div>
				<YouTube
					url={this.state.video}
					opts={opts}
					onReady={::this.onReady}
					onPlay={::this.onPlay}
					onPause={::this.onPause}
					onEnd={::this.onEnd}
					onError={::this.onError}
				/>
			</div>
		);
	}
}

ReactDOM.render(
	<Test />,
	document.getElementById('app')
);
```
I'm gonna debug this some more and hopefully figure out what is going wrong here...

**Comment by troybetz** [comment]
Very weird, will dig into this today!

**Comment by tjallingt** [comment]
Hey thanks for responding :)

It seems that the issue comes from not correctly destroying the player...
When it gets loaded really quickly the first time this piece of code doesn't happen because of the delay before the `createPlayer` callback
```javascript
 if (this._internalPlayer) {
      this._internalPlayer.destroy();
 }
```
Because the player gets created twice on the same element the youtube iframe api returns an empty player object the second time, this empty player gets set as the `_internalPlayer` and then the actual player that is on the page doesn't get propperly destroyed which makes all subsequent players also fail.

In my app this also happens when i click the

**Comment by troybetz** [comment]
Huge, huge thanks for taking the time to check this out! #29 definitely needs to go through soon I've been putting it off for too long.

And honestly, if you want to do the rewrite I'm all for it. It'd legit be my first time accepting a PR that extensive so we'd both be learning in the process!. But either way, that rewrite is inevitable and shouldn't take *too* long so don't to waste your time with the other solutions (as much as I seriously appreciate you thinking them out!).

 I'll create a branch to explore it right now. If you're up for it, join in

**Comment by tjallingt** [comment]
Thank you :D 
I already ported the basic functionality (playing videos, haha), and will commit them to the rewrite branch soon.

**Comment by tjallingt** [comment]
```remote: Permission to compedit/react-youtube.git denied to tjallingt.```
:cry: 

I attempted to update the dependencies and fix the tests as well but ran into some nasty problems...
Not sure whether I can manage to rewrite the tests by myself as I have almost no experience writing tests and due to the abstraction of the youtube api by `youtube-player` I'm not sure how to do most of the tests anyway.

**Comment by troybetz** [comment]
Oops that's mybad, I should have mentioned. You need to open a pull request, so we can do something [like this](https://github.com/troybetz/react-soundcloud-widget/pull/7). 

Check [this](https://guides.github.com/introduction/flow/) out for the general idea. [This guide](https://help.github.com/articles/using-pull-requests/) walks you through the process a little more in depth. Just copy/paste the changes you've made and push them to your fork, then open a pull request and all that

If you have any questions, let me know! We can talk more about the code in the PR. And I wouldn't worry about the tests for now, going to have to rewrite them too so it's all good

**Comment by tjallingt** [comment]
I managed, thanks for the help :D
