### ISSUE TITLE
Easiest way of using the project outside of node.js environment? 

### ISSUE THREAD

**Issue by eleweek** [troybetz/react-youtube#39]
Hi, I am new to the JS world, sorry if this is a newbie question. I've only recently started learning react.js , and I'd like to use react-youtube for my current project(which I am doing for fun). My current backend is a simple Sinatra app, and I am trying to avoid using node.js infrastructure(like npm). 

I tried doing `npm install` in react-youtube dir and then dropping `YouTube.js` and `lib/createPlayer.js` as static files into my project. That didn't work. Then I tried concatenating both files into a single file. That didn't work too. Then I added `require.js` to my project, but I still get an error:

```
Error: Module name "get-youtube-id" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
```

Ideally I'd like to add a few files to `/static` directory and include them as <script src=...></script>. Also, I am ok with quick&dirty way of doing this(my project is at prototype stage anyway, and I am not sure if it'll work as good as I want it to work!)

**Comment by tjallingt** [comment]
Hey,
I think `require.js` cannot find the `get-youtube-id` because it isn't located in your `/static` folder. If you want to use `require.js` with `react-youtube` you will first need to bundle all of its dependencies in a single file (just concatenating `Youtube.js` and `lib/createPlayer.js` isn't enough).
This can be done using a tool like `browserify` which creates a javascript bundle that you can then `require`. 

> [...] I am trying to avoid using node.js infrastructure(like npm).

Any particular reason for this? Using `browserify` and `babelify` can help a lot when writing front end javascript (and makes your code relatively future proof).

Hope this helps...

**Comment by troybetz** [comment]
Like @tjallingt said, in general you'll be much happier with a node.js based workflow!

But just for you, [here's a quick & dirty UMD build of react-youtube](https://gist.github.com/troybetz/b740a3b8dc092b7daa70) and [here's the webpack config I used to generate it](https://gist.github.com/troybetz/1c013e6eb55da01d40a9) 😀. You can include it via a script tag and it'll be available as `window.ReactYouTube`, make sure React is included before it!

[Here's an example of it being used](https://jsfiddle.net/k6unu1ds/), note `ReactYouTube.js` being included under external resources. Hope that helps!

**Comment by eleweek** [comment]
@tjallingt @troybetz Thanks a lot! 

> Any particular reason for this? Using browserify and babelify can help a lot when writing front end javascript (and makes your code relatively future proof).

No real reason, I am somewhat lazy, and it just seems like an overkill for the small project I'm working on.   

Also, thanks a lot of for the explanation! After reading it, I read about AMD/require.js and now I have much better understanding of what went wrong. 

> But just for you, here's a quick & dirty UMD build of react-youtube and here's the webpack config I used to generate it 

Thanks a lot! ^_^
