### ISSUE TITLE
Upgrade Babel to 6.0.0+

### ISSUE THREAD

**Issue by tjallingt** [troybetz/react-youtube#40]
Babel 6.0.0+ is quite different from pre 6.0.0 in that it now has no functionality of its own any more and just supports the loading of packages that will transpile your code. I didn't upgrade it earlier because it was still quite fresh (and I didn't read up on the details of the changes yet). I think upgrading is probably a good idea and all that needs to happen is some changes to the `package.json` and `.babelrc`.

Should I just push the changes to the `rewrite` branch or what is the best strategy here?

**Comment by troybetz** [comment]
Rewrite branch sounds good to me!

**Comment by tjallingt** [comment]
Done!
