### ISSUE TITLE
Support of react 14?

### ISSUE THREAD

**Issue by lapanoid** [troybetz/react-youtube#43]
Hello, thanks for your component!
I am updating my project to react 14 and as I use react-youtube component currently it is peerDependacy problem, I have started to make changes and wished to make PR but noticed that you have rewrite branch with react 14. 
Do you have some estimate when it will be merged with master and published?
Thanks!

**Comment by tjallingt** [comment]
The release date is completely up to @troybetz, but I agree an eta would be a good idea.

All that really needs to happen before publishing it on `npm` is a major version bump seeing as the `rewrite` branch is already feature complete. 

In the meantime you can try using the `rewrite` branch using `npm`'s "[github url as a dependency](https://docs.npmjs.com/files/package.json#github-urls)"-feature like this: `"react-youtube": "troybetz/react-youtube#rewrite"`

I personally had mixed results with this method but maybe you can figure out how to make it work...

**Comment by troybetz** [comment]
Sorry for the late reply @lapanoid, been swamped on the side. 5.0.0 should be out in a few days, will close this when it's out

**Comment by goto-bus-stop** [comment]
@troybetz friendly ping :) is anything blocking v5 still? i'd be happy to help out if so!

**Comment by troybetz** [comment]
Sorry, on it!

**Comment by troybetz** [comment]
5.0.0 is available & supports react 14, sorry for the wait!

**Comment by goto-bus-stop** [comment]
all good! many thanks! :)
