### ISSUE TITLE
Getting warning message: "React component classes must extend React.Component", component not rendering

### ISSUE THREAD

**Issue by BenPiggot** [troybetz/react-youtube#51]
The plug-in was working until my team upgraded to the React 0.14.3 for our current project. My assumption is that the problem is related to versioning/compiling, but I can't figure it out looking at the source code.

**Comment by tjallingt** [comment]
From what you are describing it appears that `react-youtube` is not the source of the problem...
React is telling you that you are attempting to use a component that is not extending `React.Component`.
`react-youtube` is clearly doing this, [see this line](https://github.com/troybetz/react-youtube/blob/master/src/YouTube.js#L14).

Please confirm that all component classes that are used in your project extend `React.Component`.
If this is the case, can you further describe the issue; is `react-youtube` the only component that fails rendering? how are you requiring `react-youtube` (browserify or other tool)? etc...

**Comment by BenPiggot** [comment]
We are not using React.Component elsewhere in the project - we are using React.createClass. We are using ES6, however. All other components successfully render - this is the only place where a Component does not appear. We are using systemjs to require all our modules. 

If you wish, I can supply code to provide more context.

**Comment by tjallingt** [comment]
Mhhh interesting...
Some code might help because it is quite unclear to me what would cause this issue.
I'm still not convinced the issue lies with `react-youtube` but I'll see if I can help regardless :)

**Comment by BenPiggot** [comment]
Ok - here is the import section of the relevant file:

```javascript
import React from 'react';
import { _, mix, mori } from 'lib/util';
import YouTube from 'react-youtube';
import UI from 'lib/ui/schema';
import Catalog from 'lib/resources/catalog';
import AdSlot from 'models/ui/core/ad-slot';
import AdPolicy from 'models/ui/ads/policy';
```

And here is the function in the module that attempts to instantiate the React component:

```javascript
  $2016Bulletin(node) {
    const ref = $2016BulletinDoc.getRefAttr(node);

    if (ref && ref.match(/https:\/\/twitter.com\//i))  {
      let embedUrl = `https://api.twitter.com/1/statuses/oembed.json?url=${ref}&callback=?`

      return <div>
        <TwitterEmbed embedUrl={embedUrl} />
        {_.map(mori.intoArray(Doc.childrenOf(node)), (c) => render2016Bulletin(c))}
      </div>;

    } else if (ref && ref.match(/https:\/\/www.youtube.com\//i)) {

        const opts = {
          height: '100%',
          width: '100%'
        }

        return <YouTube url={ref} opts={opts} />

    } else {
      return _.map(mori.intoArray(Doc.childrenOf(node)), (c) => render2016Bulletin(c))
    }
  }
 ```

I should also note that we are using version 4.1.2 of your plugin. The YouTube.js file we are importing via npm is written in ES5 (which seems different than the current version at Github?)

**Comment by tjallingt** [comment]
Version 4.1.2 (the previous version) was also written in es6, on npm install everything gets compiled down to es5 with babel, I presume that this explains what you are seeing.

From the code provided I can't tell where the problem would lie so I'll have to speculate but I think it might have to do with systemjs and the way you are compiling your es6 code (babel/traceur/?).

I can think of three options to debug/attempt to solve:

1. Download the raw of the latest version of `react-youtube` and include it in your project in the same way you are using the `TwitterEmbed`, see if the problem persists. Please to note that version 5.0.0 does not use the `url` parameter and instead uses `videoId`, you can use [get-youtube-id](https://www.npmjs.com/package/get-youtube-id) to solve that problem.
2. Create a small "hello world" component in es6 with `extends React.Component` to see whether that works.
3. Create a minimal reproduction of the issue; a small app that imports `react-youtube` with systemjs and compiles the es6/jsx code. This allows us the better test what causes the problem.

Perhaps its a good idea to try installing the latest version anyway, it might just fix the issue (you never know...)

**Comment by BenPiggot** [comment]
Thanks! I appreciate your help - I'll try some of the above and let you know how it works out.

**Comment by abeyuya** [comment]
I have same issue...
I will share how it works if I solve.

**Comment by troybetz** [comment]
I would definitely follow @tjallingt's advice if possible and try out the latest version, but if that's not possible would either of you mind sharing a small repo reproducing the issue? Sorry for the trouble, and thanks!

**Comment by tjallingt** [comment]
@abeyuya can you further describe your problems? Are you also using systemjs? Which version or react-youtube are you using? Etc.

**Comment by abeyuya** [comment]
I have solved this problem when create `a small repo reproducing `!  :smiley: 

My problem was just `Please confirm that all component classes that are used in your project extend React.Component`.

My bad code used React.createClass.
When replace all of React.createClass to React.Component ES6 style, new code run correctly.

This is my transpile settings. https://github.com/abeyuya/react-youtube-issue-51
(Not include reproducing code.)

When I use both React.createClass and React.Component, this code was broken.
When I use only React.Component (and react-youtube), this code run correctly.

Thank you for your support!!

**Comment by tjallingt** [comment]
Great that you managed to find a fix!
Ill take a look at your reproduction (thanks for creating it :+1:) to find out what exactly causes this error.

**Comment by troybetz** [comment]
@abeyuya glad to hear it! Very weird though.

@BenPiggot if you're still having problems, feel free to reopen this
