### ISSUE TITLE
Support server-side rendering

### ISSUE THREAD

**Issue by tjallingt** [troybetz/react-youtube#57]
See:
https://github.com/koistya/react-static-boilerplate/issues/66#issuecomment-174240769

**Comment by tjallingt** [comment]
@troybetz, can you publish c6e724dd0281da428f4f4acb6a6f39cde055e064? I need the changes to `youtube-player` to test the changes to `react-youtube` :worried:

**Comment by benigeri** [comment]
Would be great to get this published. :)

**Comment by tjallingt** [comment]
I'm so sorry for the delay, it's published now and everything should work correctly :)
