### ISSUE TITLE
OnReady -> .playVideo() doesn't work

### ISSUE THREAD

**Issue by yizhexia** [troybetz/react-youtube#62]
It was working in 4.X but after upgrading to 5.1, it seems to now be broken.

**Comment by yizhexia** [comment]
Can somebody see if they can replicate this? 

I'm suspecting my code may be the culprit rather than the component. That being said, I didn't touch anything in-between the upgrade so I'm not quite sure which is at fault.

**Comment by tjallingt** [comment]
You can set the `autoplay` option to achieve the same result...
I tried it out but it doesn't seem to work for me either

```
onReady = (event) => {
	this.setState({ youtube: event.target });
	event.target.playVideo();
};
```
Doesn't work while it should, once I have time I'll look into it. :+1:

**Comment by tjallingt** [comment]
https://github.com/troybetz/react-youtube/pull/63 fixes this behaviour :smile:
I'll publish this on npm soon.
