### ISSUE TITLE
Pausing video externally

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [troybetz/react-youtube#66]
How to pause youtube video externally like clicking on a button.

**Comment by goto-bus-stop** [comment]
There's no prop to do this, but you can get to the internal YouTube player API using a React ref:

```js
class MyComponent extends React.Component {
  pause() {
    const player = this.refs.youtube._internalPlayer;
    player.pauseVideo();
  }
  render() {
    return (
      <YouTube
        ref="youtube"
        {...this.props}
      />
    );
  }
}
```

However a `paused` prop could be a cool feature:

```js
<YouTube videoId="_lj7vcmZLPE" paused />
```

**Comment by HarshaVardhanPVK** [comment]
I stored the event of the video in a state (in onPlay()) and with help of that event I paused video (event.target.pauseVideo())

**Comment by nameisys** [comment]
@goto-bus-stop 
Hi! I tried your recommendation but i got this when i fire 'pause()'.
"Uncaught TypeError: Cannot read property 'pauseVideo' of undefined" 

What did I wrong?😭

**Comment by goto-bus-stop** [comment]
@nameisys The internal property name has changed since then. A better way to do it is to store the player like HarshaVardhanPVK mentioned:

```js
class MyComponent extends React.Component {
  // Store a reference to the internal player object when it's ready.
  onPlayerReady (event) {
    this.player = event.target
  }
  pause () {
    this.player.pauseVideo()
  }
  render () {
    return (
      <YouTube
        onReady={this.onPlayerReady.bind(this)}
        {...this.props}
      />
    )
  }
}
```

**Comment by nameisys** [comment]
@goto-bus-stop 
I got result what I want. :) Thanks for your help!
