### ISSUE TITLE
Support for onPlaybackQualityChange

### ISSUE THREAD

**Issue by jesnil01** [troybetz/react-youtube#69]
Any plans of adding support for the event returned when playbackquality is changed?

**Comment by tjallingt** [comment]
Youtube Iframe API supports the following events of which the selected events are supported by `react-youtube`;
- [x] onReady
- [x] onStateChange
- [ ] onPlaybackQualityChange
- [ ] onPlaybackRateChange
- [x] onError
- [ ] onApiChange
I'm not sure why some of the events are missing and that there is a strong case for supporting them (at least at first glance). 
Would you like to create a pull-request containing these events?

**Comment by tjallingt** [comment]
Fixed by https://github.com/troybetz/react-youtube/pull/70 :smile:
