### ISSUE TITLE
Full screen is unavailable

### ISSUE THREAD

**Issue by sandervanhooft** [troybetz/react-youtube#72]
Hi @troybetz ,

I've tried the react-youtube component and it seems to work well. However there's one issue: the fullscreen button in the bottom right corner is disabled. When clicked it shows a small popup message stating:

> Full screen is unavailable. [Find out more](https://support.google.com/youtube/answer/6276924)

It seems to be unrelated to the browser (tested both Safari and Chrome). When visiting Youtube.com and opening a video the fullscreen button works as expected. I've also tried to pass `allowfullscreen: 1` and `fs:1` using `opts`. No luck there. Also tried different video's.

Any clue what's going on here? Or how I can debug it further?

Kind regards,

Sander

**Comment by tjallingt** [comment]
Please try cloning `react-youtube` onto your machine and then running `npm run example`.
If you open `localhost:8080` in your browser you are presented with a simple example of `react-youtube`, does the problem also occur on this page?

Perhaps try to create a simple page that loads a video using the Youtube Iframe API (if needed I could quickly create it for you) and check whether the same problem occurs.

**Comment by sandervanhooft** [comment]
@tjallingt Thank you. `npm run example` does not yield this problem.

When running react-youtube in [react-storybook](https://github.com/kadirahq/react-storybook) the problem persists. It seems to be using [react-split-pane](https://github.com/tomkp/react-split-pane) under the hood. This uses an iframe, so perhaps this is the cause?
