### ISSUE TITLE
"The node to be removed is not a child of this node." when unmounting component in React v15

### ISSUE THREAD

**Issue by goto-bus-stop** [troybetz/react-youtube#74]
When the YouTube component is unmounted in React v15, this happens:

```
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
removeChild	@	DOMChildrenOperations.js:66
```

The stack trace isn't particularly useful because it's just ~100 layers of internal React calls.

However a breakpoint is more helpful:

![scope screenshot](http://i.imgur.com/aOoh6XJ.png)

Here `childNode` is a __div__ element with id `player_1`, but the actual element in the DOM is an iframe. I suspect this is because the YouTube API replaces the `player_1` element with its own, and React doesn't notice that it was replaced.

One way to fix this might be to create the `<div id="player_1">` manually using `document.createElement` in `componentDidMount`. I'll try a few things and send a PR :v:

**Comment by goto-bus-stop** [comment]
This is the same kind of problem as described here, for context: facebook/react#6593

**Comment by tjallingt** [comment]
The `destroyPlayer()` call undoes all changes made by the Youtube Iframe API. So I'm not sure why React would complain about not being able to find the div...

**Comment by goto-bus-stop** [comment]
Oh, huh. I think it's because [youtube-player](https://github.com/gajus/youtube-player) puts all method calls in a promise `.then` handler, which means the _actual_ destroyPlayer() call is done on the next tick, after `componentWillUnmount` has finished. https://github.com/gajus/youtube-player/blob/master/src/YouTubePlayer.js#L43-L58

**Comment by goto-bus-stop** [comment]
(There might still be a better way around it than my proposed fix, though.)

**Comment by tjallingt** [comment]
That is probably what is happening yea...
Ideally `youtube-player` would allow us to call `destroy` synchronously (like `this._internalplayer.synchronous.destroy()` or something).
Maybe it is worth submitting a pull request for this type of functionality?

Although your solution works and is pretty clean I'd like to just use the method of the Youtube Iframe API that was created for this exact reason :smile:

**Comment by goto-bus-stop** [comment]
Yeah, definitely, that would be best. I'll send a PR to youtube-player and see how it goes.

**Comment by goto-bus-stop** [comment]
…OTOH, that synchronous access would pretty much only be useful for this use case. I can't think of any situation where it'd be used except "I need to destroy the player and I need to destroy it in _this tick_".

I don't think any solution is ideal here :sweat_smile:
