### ISSUE TITLE
React Facebook Player

### ISSUE THREAD

**Issue by fmedinac** [troybetz/react-youtube#80]
Hey there,
Thank you for this, really helped me with my project.

I'm here to let you know that I created a project for embedding Facebook video player that's completely based on your, I reused good part of your structure, hope you don't mind. ;)

https://github.com/fmedinac/react-facebook-player

Txs,
Medina

**Comment by tjallingt** [comment]
Hey @fmedinac,

Sorry for the slow response :sweat: 
It's great to hear that this project helped/inspired you to create your own project!
Reusing part of our code is no problem, it is open source after all (and you even included a nice reference back to this project).
I might put your project in a `derived/related works` section in our readme (i'll have to check what others call such a section haha), perhaps any of our users are also interested in Facebook videos.

(also i'll close this issue for reasons i hope are clear :smile:)
