### ISSUE TITLE
getVideoData() in onReady

### ISSUE THREAD

**Issue by ChocoMomo** [troybetz/react-youtube#81]
Using event.target.getVideoData() in the onReady Handler the "video title" and "video author" are somehow empty.

**Comment by tjallingt** [comment]
Hello @ChocoMomo 

When i modify our example application to include a call to `getVideoData()` it returns:
```javascript
Object {video_id: "XxVg_s8xAms", author: "", title: "Introduction to React.js"}
```
I verified that `author` is indeed empty which is strange however when I looked into the [official YouTube Iframe API documentation](https://developers.google.com/youtube/iframe_api_reference) it appears that `getVideoData()` is an undocumented feature. This means that there are no guarantees that the method will continue to function/exist in the future.
If you want to retrieve the video title and author for a given video (of which you have the

**Comment by ChocoMomo** [comment]
Thanks for the help.

In the documentation they said that the onReady event does not specify a data property. So this is why it doesn't work.

Now i use another approach to get the video data. By using the onStateChange handler afterwards i can get the right video data. I used this for event tracking in my application

This issue can be closed
