### ISSUE TITLE
How to stop player from js?

### ISSUE THREAD

**Issue by Rash96** [troybetz/react-youtube#88]
My problem.  I have several player-components on my page and when one player starts other players have to stop.

**Comment by Rash96** [comment]
My problem.  I have several player-components on my page and when one player starts other players have to stop.

**Comment by tjallingt** [comment]
Hey @Rash96 
In the example you can see how to pause a video: https://github.com/troybetz/react-youtube/blob/master/example/example.js#L34-L36
In your case you probably want to do something like:
```js
setPlayer(event, number) {
  players = this.state.players;
  players[number] = event.target;
  this.setState({
    players: players,
  });
}

pauseOtherPlayers(number) {
  this.state.players.forEach((player, index) => {
    if (number !== index) {
      player.pauseVideo();
    }
  });
}

render() {
  return {
    <YouTube
      videoId={videoId[0]}
      opts={/* opts */}
      onReady={(event) => setPlayer(state, 0)}
      onPlay={() => pauseOtherPlayers(0)}
    />
    <YouTube
      videoId={videoId[1]}
      opts={/* opts */}
      onReady={(event) => setPlayer(state, 1)}
      onPlay={() => pauseOtherPlayers(1)}
    />
    // repeat for other players
  }
}
```
:warning: I did not test this so there is no guarantee this works as is. This example also might not be the best way of doing this but it should help you figure out the rest yourself...

**Comment by Rash96** [comment]
@tjallingt Thanks a lot! I understand your idea)
