### ISSUE TITLE
Force playback quality

### ISSUE THREAD

**Issue by SpaceK33z** [troybetz/react-youtube#90]
Currently it seems not possible to force the playback quality to a given value.

The IFrame Player API exposes the [`setPlaybackQuality`](https://developers.google.com/youtube/iframe_api_reference#Playback_quality) method for this. Would it be possible to set the quality as an option, and let this library internally call `setPlaybackQuality`?

The use-case for this is that we're running a TV dashboard on a Raspberry Pi, which doesn't seem to be able to handle high-quality video. Of course there are more use-cases for this, e.g. when the player is very small it isn't necessary to use high-quality.

I could make a PR for this.

**Comment by tjallingt** [comment]
```js
class Example extends React.Component {
  _onReady = (event) => {
    this.setState({ player: event.target });
  };
  
  _onPlay = () => {
    this.state.player.setPlaybackQuality('medium');
  };

  render() {
    return (
      <YouTube
        videoId=/* videoId */
        onReady={this._onReady}
        onPlay={this._onPlay}
      />
    );
  }
}
```

This is how I'd suggest to implement this functionality.
I don't think it's a good idea to implement this functionality as a prop because it has some behaviour that does not fit the expectations of a prop:

> This function sets the suggested video quality for the current video. The function causes the video to reload at its current position in the new quality. If the playback quality does change, it will only change for the video being played. **Calling this function does not guarantee that the playback quality will actually change.**
> [...]
> If you call the setPlaybackQuality function with a suggestedQuality level that is not available for the video, then the quality will be set to the next lowest level that is available. 

I'd like to hear some other people comment on this issue as perhaps a `desiredPlaybackQuality` could be useful...

**Comment by SpaceK33z** [comment]
Thanks for your answer. I implemented this yesterday already in my fork because I really needed it: https://github.com/SpaceK33z/react-youtube/commit/6bb22c4fec16331d55b62caec72f68874ee01fce.  In my manual tests it always changed the quality.

I could change the prop to `desiredPlaybackQuality` though, that would make more sense indeed.

**Comment by PaschalisSk** [comment]
Somehow some years ago I found that you can have vq inside playerVars to change the quality
`playerVars: {
    vq: 'large'
  }`

For some reason 'large' is 720p and 'hd720' is actually setting it to 1080p.
