### ISSUE TITLE
Uncaught ReferenceError: ytcfg is not defined

### ISSUE THREAD

**Issue by d4nyll** [troybetz/react-youtube#91]
I'm doing a very simple embed example, and it comes back with the following error. This happened just in the past few hours. During my search, I have also noticed a similar [issue](https://github.com/ArunMichaelDsouza/ng-youtube-embed/issues/7) on a Angular YouTube embed package, the issue may be related.

```
Uncaught ReferenceError: ytcfg is not defined
    at https://www.youtube.com/embed/?enablejsapi=1&origin=http%3A%2F%2Flocalhost%3A3000&widgetid=1:10:15420
```

(Sorry no time to create a repo to document the bug properly)

**Comment by rwilson** [comment]
I just started seeing this in the last day as well, but it's inconsistent and, oddly, I'm not even rendering the YouTube component every time it happens. So it seems sufficient only that the module be imported , but also not 100% of page loads.

**Comment by tjallingt** [comment]
Hey, this seems to be an issue on YouTube's end (from what i read by googling the error message) so I don't think there is anything we can do about it. Please comment here if there is any new information on this issue however 😄
