### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow

### ISSUE THREAD

**Issue by 123ndy** [troybetz/react-youtube#96]
I get this message in console: `Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://mydomain.com').`

I have read that a combo of `http` and `https` could be the reason, but in this case both the iframe and the hosted domain is using https. 

Any idea of what it can be?

**Comment by JulianJorgensen** [comment]
Ditto here

**Comment by tjallingt** [comment]
I'm actually not sure, as you might have noticed this error message does not appear very consistently (at least it doesn't for me) and it does not affect the YouTube player functionality. We depend on a chain of NPM modules to load the YouTube player for us so it is also not possible for us to fix this issue inside this module.

**Comment by goto-bus-stop** [comment]
Yeah, it also sometimes happens when only using the official YouTube JS API. Try refreshing https://gateway.ipfs.io/ipfs/Qmb3ggu57cXHTh3JxCCF4cY3Sds21d4UdZZe6T3W5GfkHL/ a few times with an open console and you should see it pop up sometimes.

**Comment by payner35** [comment]
I was expecting this to sort it..  ?  still have some sporadic errors.

```
 playerVars: { // https://developers.google.com/youtube/player_parameters
                       origin: 'https://mywebsite.com',
                       enablejsapi: '1',

```

**Comment by mouhsinelonly** [comment]
did any one find a solution for this ?

**Comment by goto-bus-stop** [comment]
Hmm i did find this just now: https://github.com/brandly/angular-youtube-embed/pull/116is

 it fixed if you add

```js
window.YTConfig = {
  host: 'https://www.youtube.com' 
} 
```

somewhere in your app, *before* using react-youtube?

**Comment by Nufflee** [comment]
@goto-bus-stop Doesn't seem to work here.

**Comment by WeiXu123** [comment]
I haven't find a solution for this issue, but I find a way to reproduce this issue. 
If you have some tools like Charles, try to block the youtube iframe get call, you will see this error in your console every time.
I checked the Google's js file, they are just running `iframe.contentWindow.postMessage`, I am guessing that maybe when the iframe content loads slow, the postMessage call was sent to the main window? Not sure how contentWindow and postMessage really work.
