### ISSUE TITLE
Re-render with playlist fails

### ISSUE THREAD

**Issue by rmammina** [troybetz/react-youtube#97]
When I initially render the youtube component with a configuration playlist parameter, the player loads the playlist correctly. EG
```
return (
<YoutubePlayer
   playbackState='unstarted'
   height="350"
   width="875"
   configuration={{
      playlist: this.props.ids
   }}
/>
)
```
However, if I update the results, player stops playing, and just reloads the playlist that I originally had provided it. Not sure if I need to wait for the player to finish destruction or what not.

**Comment by vivekparekh8** [comment]
How do you solve playlist issue ?
How to show playlist using this component ?
